<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Путеводитель форма</title>
</head>
<body>
	
<?php
	//Получаем данные из модели
	if (Zend_Registry::isRegistered('model'))
		{
		$model = Zend_Registry::get('model');
		$this->form->options = $model->locationsList;
		array_unshift($this->form->options,"none");
		$path = $model->pathTextComment;
		if(isset($path))
			$this->form->textPathComment = $path;
		}
		
	$this->form->refresh();	
	echo $this->form;
?>

</body>
</html>
