<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Путеводитель таблицы</title>
</head>
<body>

<?php

Out("Использован вывод таблиц.");

class TMyTableView
	{
	private $PagesCount;
	private $RowCount;
	private $ColCount;

	private function DataAnalyse()	
		{
		//Функция проверяет являются ли данные таблицей
		//Определяем размерность массива
		$Curr=$this->DataToView;
		while(count($Curr)>1)
			{
			$Curr=$Curr[0];			
			$i++;
			}
		//Out("i=$i");
		
		if($i>3){Out("Ошибка размерности массива входных данных");return;}
		
		$Curr=$this->DataToView;
		if($i==3)
			{
			$this->PagesCount=count($Curr);
			$Curr=$Curr[0];
			$i--;
			}
		if($i==2)
			{
			$this->RowCount=count($Curr);
			$Curr=$Curr[0];
			$i--;
			}
		if($i==1)
			{
			$this->ColCount=count($Curr);
			$Curr=$Curr[0];
			$i--;
			}
		// Сначала идёт Row, потм Col
		return $i;
		}
		
	private function PrintTable($Table,$Header="",$Name="")	
		{
		//проверяем корректность ввода
		$RowCount=count($Table);
		$Row = $Table[0];
		$ColCount=count($Row);
		if($ColCount<2&&$RowCount<2){Out("Ошибка размерности массива входных данных");return;}
		// Выводим заголовок таблицы:
		if($Name!="")
			echo "$Name";
		echo "<table border=\"1\" width=\"100%\" bgcolor=\"#FFFFE1\">";
		if($Header!="")
			{
			echo "<tr>";
			for ($i=0; $i<$ColCount; $i++)
				{
				$Out=$Header[$i];
				echo "<td>$Out</td>";
				}
			echo "</tr>";
			}
		// Выводим саму таблицу:
		for ($i=0; $i<$RowCount; $i++)
			{
			echo "<tr>";
			$Row = $Table[$i];
			for ($j=0; $j<$ColCount; $j++)
				{
				$td = $Row[$j];
				echo "<td>$td</td>";
				}
			echo "</tr>";
			}
		echo "</table>";
		}

	//Основной интерфейс
	public function Show()		//Показывает всё
		{
		$this->DataAnalyse();
		if($this->PagesCount>0)
			for ($i=0; $i<$this->PagesCount; $i++)
				{
				if(isset($this->TableHeader[$i]))$Header=$this->TableHeader[$i];
				if(isset($this->TableNames[$i]))$Name=$this->TableNames[$i];
				$this->PrintTable($this->DataToView[$i],$Header,$Name);
				}
		else
			$this->PrintTable($this->DataToView,$this->TableHeader[0],$this->TableNames[0]);	//плохо работает
		}

	public $DataToView;
	public $TableHeader;
	public $TableNames;
	}
	
//Получаем данные из модели
$registry = Zend_Registry::getInstance();
$model = $registry -> get('model');

//Выводим 3 таблицы
$View1 = new TMyTableView;

$Table=$model->db->Get("AnuireLocations");
//$Table=$testTable;
$Header=array("No","X","Y","Название","Описание","Размер");
$Name="Локации Ануира";
$Headers[]=$Header;
$Tables[]=$Table;
$Names[]=$Name;

$Table=$model->db->Get("RoadsView");
$Header=array("No","Откуда","Куда");
$Name="Дороги Ануира";
$Headers[]=$Header;
$Tables[]=$Table;
$Names[]=$Name;

$Table=$model->db->Get("Points");
$Header=array("No","X","Y","Z");
$Name="Точки на карте";
$Headers[]=$Header;
$Tables[]=$Table;
$Names[]=$Name;

$View1->DataToView=$Tables;
$View1->TableHeader=$Headers;
$View1->TableNames=$Names;
$View1->Show();
?>

</body>
</html>

