<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Путеводитель карта</title>
</head>
<body>
Карта Ануира.
Города обзначены чёрным цветом. Дороги между городами обозначены красным. 
Кратчайший путь между двумя городами на карте отрисовывается синими стрелками.
Незначительнве детали обозначены белым цветом.
	
<img src="/home/earthundead/Programs/www/Zend/application/data/map.png"  width="100%" height="95%" alt="Error">

</body>
</html>
