<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF8">
	<title>Путеводитель карта</title>
</head>
<body>
Карта Ануира.
Города обзначены чёрным цветом. Дороги между городами обозначены красным. 
Кратчайший путь между двумя городами на карте отрисовывается синими стрелками.
Незначительнве детали обозначены белым цветом.
	
<img src="/home/earthundead/Programs/www/Zend/application/data/map.png"  width="100%" height="90%" alt="Error">

<?php
echo "";
//<img src="/home/earthundead/Programs/www/Zend/application/data/map.png"  width="100%" height="100%" alt="Error">	
/*$registry = Zend_Registry::getInstance();
$dataFilesPath 	= $registry -> get('dataFilesPath');
$imgform = new Zend_Form;
$element = new Zend_Form_Element_Image('Image1');
$element->setRequired(true);
$element->setLabel("Map of anuire");
$element->setImage($dataFilesPath . "/map.png");
$imgform->addElement($element);
echo $imgform;*/

/*$registry = Zend_Registry::getInstance();
$dataFilesPath 	= $registry -> get('dataFilesPath');
$imagesClass = new Application_Model_Images;
//$image=imagecreatefrompng($dataFilesPath . "/map.png");
$image = imagecreate(1000,1000);
$color = imagecolorallocate($image,0,0,0);
imageline($image,10,10,200,200,$color);
$imagesClass->img = $image;
$imagesClass->ImageOut();*/
?>

</body>
</html>
